FROM alpine:latest

LABEL org.opencontainers.image.authors="Diamond Drake Ventures"
LABEL org.opencontainers.image.source="https://github.com/diamonddrakeventures/yolks"
LABEL org.opencontainers.image.licenses="MIT"

RUN apk add --update --no-cache \
    bash \
    ca-certificates \
    curl \
    git \
    jq \
    openjdk21 \
    wget
