name: Build Java images
on:
  push:
    paths:
      - ".github/workflows/java.yaml"
      - "java/**"
    branches:
      - "*"
    tags:
      - "*"

permissions:
  packages: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        java: [ "21" ]
    runs-on: ubuntu-24.04
    name: Build Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./java/${{ matrix.java }}
          file: ./java/${{ matrix.java }}/Dockerfile
          push: true
          tags: |
            ghcr.io/diamonddrakeventures/yolks/java:${{ matrix.java }}
